name: Tourism Project Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r tourism_project/requirements_ci.txt
      - name: Register Dataset
        run: python tourism_project/model_building/data_registration.py

  data-prep:
    runs-on: ubuntu-latest
    needs: register-dataset
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r tourism_project/requirements_ci.txt
      - name: Data Preparation
        run: python tourism_project/model_building/data_preparation.py

  model-training:
    runs-on: ubuntu-latest
    needs: data-prep
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r tourism_project/requirements_ci.txt
      - name: Train Model
        run: python tourism_project/model_building/model_building.py

  deploy-hosting:
    runs-on: ubuntu-latest
    needs: model-training
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r tourism_project/deployment/requirements.txt
      - name: Deploy
        run: python tourism_project/deployment/hosting.py
